### ISSUE TITLE
loglevel param isn't working

### ISSUE THREAD

**Issue by Ryan-McMillan** [tivac/dullard#118]
Using --loglevel=silly, --loglevel=verbose etc. doesn't appear to be working.  --silly and --verbose do work though.

**Comment by Ryan-McMillan** [comment]
Noticed that this may have changed to --log, but there's still some references to --loglevel in the readme, so maybe this is just a documentation bug

**Comment by tivac** [comment]
Fixed the one instance of `loglevel` I found, if there are any others reopen and I can kill 'em!
